export type Product = {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  category: string;
  categorySlug: string;
  description: string;
  features: string[];
  image: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
};

export const PRODUCTS: Record<string, Product> = {
  prod_001: {
    id: 'prod_001',
    name: 'Backpack',
    price: 99,
    originalPrice: 651,
    category: 'Bags & Travel',
    categorySlug: 'bags-travel',
    description: 'High quality backpack generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/backpack.png',
    rating: 4.9,
    reviewCount: 378,
    inStock: true,
  },
  prod_002: {
    id: 'prod_002',
    name: 'Bluetooth Speaker',
    price: 275,
    originalPrice: 745,
    category: 'Audio',
    categorySlug: 'audio',
    description: 'High quality bluetooth speaker generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/bluetooth_speaker.png',
    rating: 4.8,
    reviewCount: 396,
    inStock: true,
  },
  prod_003: {
    id: 'prod_003',
    name: 'Candle Set',
    price: 276,
    originalPrice: 741,
    category: 'Home & Decor',
    categorySlug: 'home-decor',
    description: 'High quality candle set generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/candle_set.png',
    rating: 4.0,
    reviewCount: 247,
    inStock: true,
  },
  prod_004: {
    id: 'prod_004',
    name: 'Canvas Belt',
    price: 77,
    originalPrice: 1169,
    category: 'Fashion & Apparel',
    categorySlug: 'fashion',
    description: 'High quality canvas belt generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/canvas_belt.png',
    rating: 4.6,
    reviewCount: 409,
    inStock: true,
  },
  prod_005: {
    id: 'prod_005',
    name: 'Chef Knife',
    price: 452,
    originalPrice: 663,
    category: 'Kitchen & Appliances',
    categorySlug: 'kitchen',
    description: 'High quality chef knife generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/chef_knife.png',
    rating: 5.0,
    reviewCount: 228,
    inStock: true,
  },
  prod_006: {
    id: 'prod_006',
    name: 'Coffee Dripper',
    price: 68,
    originalPrice: 900,
    category: 'Kitchen & Appliances',
    categorySlug: 'kitchen',
    description: 'High quality coffee dripper generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/coffee_dripper.png',
    rating: 4.1,
    reviewCount: 76,
    inStock: true,
  },
  prod_007: {
    id: 'prod_007',
    name: 'Coffee Maker',
    price: 401,
    originalPrice: 798,
    category: 'Kitchen & Appliances',
    categorySlug: 'kitchen',
    description: 'High quality coffee maker generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/coffee_maker.png',
    rating: 4.1,
    reviewCount: 159,
    inStock: true,
  },
  prod_008: {
    id: 'prod_008',
    name: 'Desk Converter',
    price: 517,
    originalPrice: 866,
    category: 'Furniture',
    categorySlug: 'furniture',
    description: 'High quality desk converter generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/desk_converter.png',
    rating: 4.7,
    reviewCount: 50,
    inStock: true,
  },
  prod_009: {
    id: 'prod_009',
    name: 'Desk Lamp',
    price: 434,
    originalPrice: 905,
    category: 'Home & Decor',
    categorySlug: 'home-decor',
    description: 'High quality desk lamp generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/desk_lamp.png',
    rating: 4.7,
    reviewCount: 102,
    inStock: true,
  },
  prod_010: {
    id: 'prod_010',
    name: 'Duffel Bag',
    price: 259,
    originalPrice: 655,
    category: 'Bags & Travel',
    categorySlug: 'bags-travel',
    description: 'High quality duffel bag generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/duffel_bag.png',
    rating: 4.1,
    reviewCount: 311,
    inStock: true,
  },
  prod_011: {
    id: 'prod_011',
    name: 'Espresso Machine',
    price: 348,
    originalPrice: 815,
    category: 'Kitchen & Appliances',
    categorySlug: 'kitchen',
    description: 'High quality espresso machine generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/espresso_machine.png',
    rating: 4.2,
    reviewCount: 17,
    inStock: true,
  },
  prod_012: {
    id: 'prod_012',
    name: 'Fashion Streetwear',
    price: 502,
    originalPrice: 1239,
    category: 'Fashion & Apparel',
    categorySlug: 'fashion',
    description: 'High quality fashion streetwear generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/fashion_streetwear.png',
    rating: 4.8,
    reviewCount: 92,
    inStock: true,
  },
  prod_013: {
    id: 'prod_013',
    name: 'Headphones',
    price: 165,
    originalPrice: 1002,
    category: 'Audio',
    categorySlug: 'audio',
    description: 'High quality headphones generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/headphones.png',
    rating: 4.4,
    reviewCount: 107,
    inStock: true,
  },
  prod_014: {
    id: 'prod_014',
    name: 'Jump Rope',
    price: 205,
    originalPrice: 1228,
    category: 'Fitness',
    categorySlug: 'fitness',
    description: 'High quality jump rope generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/jump_rope.png',
    rating: 5.0,
    reviewCount: 67,
    inStock: true,
  },
  prod_015: {
    id: 'prod_015',
    name: 'Keyboard',
    price: 138,
    originalPrice: 1214,
    category: 'Electronics',
    categorySlug: 'electronics',
    description: 'High quality keyboard generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/keyboard.png',
    rating: 4.7,
    reviewCount: 304,
    inStock: true,
  },
  prod_016: {
    id: 'prod_016',
    name: 'Luxury Watch',
    price: 220,
    originalPrice: 565,
    category: 'Luxury Accessories',
    categorySlug: 'accessories',
    description: 'High quality luxury watch generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/luxury_watch.png',
    rating: 4.5,
    reviewCount: 406,
    inStock: true,
  },
  prod_017: {
    id: 'prod_017',
    name: 'Office Chair',
    price: 510,
    originalPrice: 981,
    category: 'Furniture',
    categorySlug: 'furniture',
    description: 'High quality office chair generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/office_chair.png',
    rating: 4.8,
    reviewCount: 369,
    inStock: true,
  },
  prod_018: {
    id: 'prod_018',
    name: 'Packing Cubes',
    price: 482,
    originalPrice: 582,
    category: 'Bags & Travel',
    categorySlug: 'bags-travel',
    description: 'High quality packing cubes generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/packing_cubes.png',
    rating: 4.4,
    reviewCount: 111,
    inStock: true,
  },
  prod_019: {
    id: 'prod_019',
    name: 'Plant Pot',
    price: 142,
    originalPrice: 893,
    category: 'Home & Decor',
    categorySlug: 'home-decor',
    description: 'High quality plant pot generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/plant_pot.png',
    rating: 5.0,
    reviewCount: 469,
    inStock: true,
  },
  prod_020: {
    id: 'prod_020',
    name: 'Resistance Bands',
    price: 199,
    originalPrice: 1191,
    category: 'Fitness',
    categorySlug: 'fitness',
    description: 'High quality resistance bands generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/resistance_bands.png',
    rating: 4.6,
    reviewCount: 57,
    inStock: true,
  },
  prod_021: {
    id: 'prod_021',
    name: 'Running Shoes',
    price: 385,
    originalPrice: 728,
    category: 'Footwear',
    categorySlug: 'footwear',
    description: 'High quality running shoes generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/running_shoes.png',
    rating: 4.4,
    reviewCount: 141,
    inStock: true,
  },
  prod_022: {
    id: 'prod_022',
    name: 'Slip On Sneakers',
    price: 211,
    originalPrice: 991,
    category: 'Footwear',
    categorySlug: 'footwear',
    description: 'High quality slip on sneakers generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/slip_on_sneakers.png',
    rating: 4.7,
    reviewCount: 446,
    inStock: true,
  },
  prod_023: {
    id: 'prod_023',
    name: 'Smartwatch',
    price: 156,
    originalPrice: 796,
    category: 'Luxury Accessories',
    categorySlug: 'accessories',
    description: 'High quality smartwatch generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/smartwatch.png',
    rating: 4.7,
    reviewCount: 445,
    inStock: true,
  },
  prod_024: {
    id: 'prod_024',
    name: 'Smart Hub',
    price: 223,
    originalPrice: 1003,
    category: 'Electronics',
    categorySlug: 'electronics',
    description: 'High quality smart hub generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/smart_hub.png',
    rating: 4.2,
    reviewCount: 48,
    inStock: true,
  },
  prod_025: {
    id: 'prod_025',
    name: 'Studio Headphones',
    price: 323,
    originalPrice: 1204,
    category: 'Audio',
    categorySlug: 'audio',
    description: 'High quality studio headphones generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/studio_headphones.png',
    rating: 4.8,
    reviewCount: 331,
    inStock: true,
  },
  prod_026: {
    id: 'prod_026',
    name: 'Sunglasses',
    price: 390,
    originalPrice: 692,
    category: 'Luxury Accessories',
    categorySlug: 'accessories',
    description: 'High quality sunglasses generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/sunglasses.png',
    rating: 4.1,
    reviewCount: 108,
    inStock: true,
  },
  prod_027: {
    id: 'prod_027',
    name: 'Throw Blanket',
    price: 545,
    originalPrice: 932,
    category: 'Home & Decor',
    categorySlug: 'home-decor',
    description: 'High quality throw blanket generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/throw_blanket.png',
    rating: 4.2,
    reviewCount: 497,
    inStock: true,
  },
  prod_028: {
    id: 'prod_028',
    name: 'Travel Mug',
    price: 94,
    originalPrice: 592,
    category: 'Kitchen & Appliances',
    categorySlug: 'kitchen',
    description: 'High quality travel mug generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/travel_mug.png',
    rating: 4.0,
    reviewCount: 100,
    inStock: true,
  },
  prod_029: {
    id: 'prod_029',
    name: 'Wallet',
    price: 393,
    originalPrice: 1169,
    category: 'Luxury Accessories',
    categorySlug: 'accessories',
    description: 'High quality wallet generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/wallet.png',
    rating: 5.0,
    reviewCount: 27,
    inStock: true,
  },
  prod_030: {
    id: 'prod_030',
    name: 'Wall Clock',
    price: 493,
    originalPrice: 955,
    category: 'Home & Decor',
    categorySlug: 'home-decor',
    description: 'High quality wall clock generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/wall_clock.png',
    rating: 4.0,
    reviewCount: 257,
    inStock: true,
  },
  prod_031: {
    id: 'prod_031',
    name: 'Water Bottle',
    price: 88,
    originalPrice: 888,
    category: 'Fitness',
    categorySlug: 'fitness',
    description: 'High quality water bottle generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/water_bottle.png',
    rating: 4.2,
    reviewCount: 490,
    inStock: true,
  },
  prod_032: {
    id: 'prod_032',
    name: 'Winter Coat',
    price: 443,
    originalPrice: 632,
    category: 'Fashion & Apparel',
    categorySlug: 'fashion',
    description: 'High quality winter coat generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/winter_coat.png',
    rating: 4.0,
    reviewCount: 197,
    inStock: true,
  },
  prod_033: {
    id: 'prod_033',
    name: 'Wireless Earbuds',
    price: 141,
    originalPrice: 916,
    category: 'Audio',
    categorySlug: 'audio',
    description: 'High quality wireless earbuds generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/wireless_earbuds.png',
    rating: 4.5,
    reviewCount: 386,
    inStock: true,
  },
  prod_034: {
    id: 'prod_034',
    name: 'Yoga Mat',
    price: 170,
    originalPrice: 816,
    category: 'Fitness',
    categorySlug: 'fitness',
    description: 'High quality yoga mat generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/yoga_mat.png',
    rating: 4.1,
    reviewCount: 508,
    inStock: true,
  },
};

export const PRODUCTS_LIST = Object.values(PRODUCTS);

export const CATEGORIES = [
  { slug: 'fashion', name: 'Fashion & Apparel', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='fashion').length },
  { slug: 'accessories', name: 'Luxury Accessories', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='accessories').length },
  { slug: 'kitchen', name: 'Kitchen & Appliances', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='kitchen').length },
  { slug: 'electronics', name: 'Electronics', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='electronics').length },
  { slug: 'furniture', name: 'Furniture', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='furniture').length },
  { slug: 'footwear', name: 'Footwear', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='footwear').length },
  { slug: 'fitness', name: 'Fitness', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='fitness').length },
  { slug: 'home-decor', name: 'Home & Decor', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='home-decor').length },
  { slug: 'bags-travel', name: 'Bags & Travel', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='bags-travel').length },
  { slug: 'audio', name: 'Audio', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='audio').length },
];

export function getProductsByCategory(slug: string): Product[] {
  return PRODUCTS_LIST.filter(index => index.categorySlug === slug);
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase();
  return PRODUCTS_LIST.filter(product => 
    product.name.toLowerCase().includes(lowercaseQuery) || 
    product.category.toLowerCase().includes(lowercaseQuery) ||
    product.description.toLowerCase().includes(lowercaseQuery)
  );
}

export function getRelatedProducts(productId: string, limit = 4): Product[] {
  const currentProduct = PRODUCTS[productId];
  if (!currentProduct) return [];
  
  return PRODUCTS_LIST
    .filter(p => p.id !== productId && p.categorySlug === currentProduct.categorySlug)
    .slice(0, limit);
}
