export type Product = {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  category: string;
  categorySlug: string;
  description: string;
  features: string[];
  image: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
};

export const PRODUCTS: Record<string, Product> = {
  prod_001: {
    id: 'prod_001',
    name: 'Backpack',
    price: 179,
    originalPrice: 1101,
    category: 'Bags & Travel',
    categorySlug: 'bags-travel',
    description: 'High quality backpack generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/backpack.png',
    rating: 4.8,
    reviewCount: 344,
    inStock: true,
  },
  prod_002: {
    id: 'prod_002',
    name: 'Bluetooth Speaker',
    price: 540,
    originalPrice: 1214,
    category: 'Audio',
    categorySlug: 'audio',
    description: 'High quality bluetooth speaker generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/bluetooth_speaker.png',
    rating: 4.3,
    reviewCount: 301,
    inStock: true,
  },
  prod_003: {
    id: 'prod_003',
    name: 'Candle Set',
    price: 316,
    originalPrice: 559,
    category: 'Home & Decor',
    categorySlug: 'home-decor',
    description: 'High quality candle set generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/candle_set.png',
    rating: 4.6,
    reviewCount: 52,
    inStock: true,
  },
  prod_004: {
    id: 'prod_004',
    name: 'Canvas Belt',
    price: 183,
    originalPrice: 1162,
    category: 'Fashion & Apparel',
    categorySlug: 'fashion',
    description: 'High quality canvas belt generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/canvas_belt.png',
    rating: 4.1,
    reviewCount: 70,
    inStock: true,
  },
  prod_005: {
    id: 'prod_005',
    name: 'Chef Knife',
    price: 124,
    originalPrice: 787,
    category: 'Kitchen & Appliances',
    categorySlug: 'kitchen',
    description: 'High quality chef knife generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/chef_knife.png',
    rating: 4.3,
    reviewCount: 314,
    inStock: true,
  },
  prod_006: {
    id: 'prod_006',
    name: 'Coffee Dripper',
    price: 107,
    originalPrice: 1051,
    category: 'Kitchen & Appliances',
    categorySlug: 'kitchen',
    description: 'High quality coffee dripper generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/coffee_dripper.png',
    rating: 4.0,
    reviewCount: 214,
    inStock: true,
  },
  prod_007: {
    id: 'prod_007',
    name: 'Coffee Maker',
    price: 187,
    originalPrice: 571,
    category: 'Kitchen & Appliances',
    categorySlug: 'kitchen',
    description: 'High quality coffee maker generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/coffee_maker.png',
    rating: 4.6,
    reviewCount: 302,
    inStock: true,
  },
  prod_008: {
    id: 'prod_008',
    name: 'Desk Converter',
    price: 430,
    originalPrice: 996,
    category: 'Furniture',
    categorySlug: 'furniture',
    description: 'High quality desk converter generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/desk_converter.png',
    rating: 4.7,
    reviewCount: 292,
    inStock: true,
  },
  prod_009: {
    id: 'prod_009',
    name: 'Desk Lamp',
    price: 425,
    originalPrice: 1206,
    category: 'Home & Decor',
    categorySlug: 'home-decor',
    description: 'High quality desk lamp generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/desk_lamp.png',
    rating: 4.6,
    reviewCount: 171,
    inStock: true,
  },
  prod_010: {
    id: 'prod_010',
    name: 'Duffel Bag',
    price: 318,
    originalPrice: 926,
    category: 'Bags & Travel',
    categorySlug: 'bags-travel',
    description: 'High quality duffel bag generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/duffel_bag.png',
    rating: 4.7,
    reviewCount: 370,
    inStock: true,
  },
  prod_011: {
    id: 'prod_011',
    name: 'Espresso Machine',
    price: 320,
    originalPrice: 1190,
    category: 'Kitchen & Appliances',
    categorySlug: 'kitchen',
    description: 'High quality espresso machine generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/espresso_machine.png',
    rating: 4.1,
    reviewCount: 102,
    inStock: true,
  },
  prod_012: {
    id: 'prod_012',
    name: 'Fashion Streetwear',
    price: 414,
    originalPrice: 551,
    category: 'Fashion & Apparel',
    categorySlug: 'fashion',
    description: 'High quality fashion streetwear generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/fashion_streetwear.png',
    rating: 4.6,
    reviewCount: 265,
    inStock: true,
  },
  prod_013: {
    id: 'prod_013',
    name: 'Headphones',
    price: 375,
    originalPrice: 1114,
    category: 'Audio',
    categorySlug: 'audio',
    description: 'High quality headphones generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/headphones.png',
    rating: 4.3,
    reviewCount: 176,
    inStock: true,
  },
  prod_014: {
    id: 'prod_014',
    name: 'Jump Rope',
    price: 441,
    originalPrice: 1153,
    category: 'Fitness',
    categorySlug: 'fitness',
    description: 'High quality jump rope generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/jump_rope.png',
    rating: 4.5,
    reviewCount: 114,
    inStock: true,
  },
  prod_015: {
    id: 'prod_015',
    name: 'Keyboard',
    price: 345,
    originalPrice: 698,
    category: 'Electronics',
    categorySlug: 'electronics',
    description: 'High quality keyboard generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/keyboard.png',
    rating: 4.0,
    reviewCount: 305,
    inStock: true,
  },
  prod_016: {
    id: 'prod_016',
    name: 'Luxury Watch',
    price: 442,
    originalPrice: 732,
    category: 'Luxury Accessories',
    categorySlug: 'accessories',
    description: 'High quality luxury watch generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/luxury_watch.png',
    rating: 4.4,
    reviewCount: 119,
    inStock: true,
  },
  prod_017: {
    id: 'prod_017',
    name: 'Office Chair',
    price: 420,
    originalPrice: 935,
    category: 'Furniture',
    categorySlug: 'furniture',
    description: 'High quality office chair generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/office_chair.png',
    rating: 4.1,
    reviewCount: 367,
    inStock: true,
  },
  prod_018: {
    id: 'prod_018',
    name: 'Packing Cubes',
    price: 289,
    originalPrice: 1221,
    category: 'Bags & Travel',
    categorySlug: 'bags-travel',
    description: 'High quality packing cubes generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/packing_cubes.png',
    rating: 4.5,
    reviewCount: 343,
    inStock: true,
  },
  prod_019: {
    id: 'prod_019',
    name: 'Plant Pot',
    price: 497,
    originalPrice: 681,
    category: 'Home & Decor',
    categorySlug: 'home-decor',
    description: 'High quality plant pot generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/plant_pot.png',
    rating: 4.4,
    reviewCount: 379,
    inStock: true,
  },
  prod_020: {
    id: 'prod_020',
    name: 'Resistance Bands',
    price: 313,
    originalPrice: 883,
    category: 'Fitness',
    categorySlug: 'fitness',
    description: 'High quality resistance bands generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/resistance_bands.png',
    rating: 4.9,
    reviewCount: 113,
    inStock: true,
  },
  prod_021: {
    id: 'prod_021',
    name: 'Running Shoes',
    price: 387,
    originalPrice: 1049,
    category: 'Footwear',
    categorySlug: 'footwear',
    description: 'High quality running shoes generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/running_shoes.png',
    rating: 4.8,
    reviewCount: 411,
    inStock: true,
  },
  prod_022: {
    id: 'prod_022',
    name: 'Slip On Sneakers',
    price: 99,
    originalPrice: 868,
    category: 'Footwear',
    categorySlug: 'footwear',
    description: 'High quality slip on sneakers generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/slip_on_sneakers.png',
    rating: 4.4,
    reviewCount: 30,
    inStock: true,
  },
  prod_023: {
    id: 'prod_023',
    name: 'Smartwatch',
    price: 274,
    originalPrice: 688,
    category: 'Luxury Accessories',
    categorySlug: 'accessories',
    description: 'High quality smartwatch generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/smartwatch.png',
    rating: 4.3,
    reviewCount: 94,
    inStock: true,
  },
  prod_024: {
    id: 'prod_024',
    name: 'Smart Hub',
    price: 320,
    originalPrice: 975,
    category: 'Electronics',
    categorySlug: 'electronics',
    description: 'High quality smart hub generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/smart_hub.png',
    rating: 4.5,
    reviewCount: 239,
    inStock: true,
  },
  prod_025: {
    id: 'prod_025',
    name: 'Studio Headphones',
    price: 424,
    originalPrice: 755,
    category: 'Audio',
    categorySlug: 'audio',
    description: 'High quality studio headphones generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/studio_headphones.png',
    rating: 4.9,
    reviewCount: 32,
    inStock: true,
  },
  prod_026: {
    id: 'prod_026',
    name: 'Sunglasses',
    price: 527,
    originalPrice: 831,
    category: 'Luxury Accessories',
    categorySlug: 'accessories',
    description: 'High quality sunglasses generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/sunglasses.png',
    rating: 4.5,
    reviewCount: 242,
    inStock: true,
  },
  prod_027: {
    id: 'prod_027',
    name: 'Throw Blanket',
    price: 368,
    originalPrice: 920,
    category: 'Home & Decor',
    categorySlug: 'home-decor',
    description: 'High quality throw blanket generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/throw_blanket.png',
    rating: 4.9,
    reviewCount: 460,
    inStock: true,
  },
  prod_028: {
    id: 'prod_028',
    name: 'Travel Mug',
    price: 101,
    originalPrice: 852,
    category: 'Kitchen & Appliances',
    categorySlug: 'kitchen',
    description: 'High quality travel mug generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/travel_mug.png',
    rating: 4.5,
    reviewCount: 425,
    inStock: true,
  },
  prod_029: {
    id: 'prod_029',
    name: 'Wallet',
    price: 329,
    originalPrice: 1002,
    category: 'Luxury Accessories',
    categorySlug: 'accessories',
    description: 'High quality wallet generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/wallet.png',
    rating: 4.1,
    reviewCount: 66,
    inStock: true,
  },
  prod_030: {
    id: 'prod_030',
    name: 'Wall Clock',
    price: 230,
    originalPrice: 907,
    category: 'Home & Decor',
    categorySlug: 'home-decor',
    description: 'High quality wall clock generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/wall_clock.png',
    rating: 4.8,
    reviewCount: 171,
    inStock: true,
  },
  prod_031: {
    id: 'prod_031',
    name: 'Water Bottle',
    price: 504,
    originalPrice: 1061,
    category: 'Fitness',
    categorySlug: 'fitness',
    description: 'High quality water bottle generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/water_bottle.png',
    rating: 4.3,
    reviewCount: 108,
    inStock: true,
  },
  prod_032: {
    id: 'prod_032',
    name: 'Winter Coat',
    price: 55,
    originalPrice: 617,
    category: 'Fashion & Apparel',
    categorySlug: 'fashion',
    description: 'High quality winter coat generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/winter_coat.png',
    rating: 4.6,
    reviewCount: 131,
    inStock: true,
  },
  prod_033: {
    id: 'prod_033',
    name: 'Wireless Earbuds',
    price: 181,
    originalPrice: 561,
    category: 'Audio',
    categorySlug: 'audio',
    description: 'High quality wireless earbuds generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/wireless_earbuds.png',
    rating: 4.9,
    reviewCount: 482,
    inStock: true,
  },
  prod_034: {
    id: 'prod_034',
    name: 'Yoga Mat',
    price: 126,
    originalPrice: 967,
    category: 'Fitness',
    categorySlug: 'fitness',
    description: 'High quality yoga mat generated authentically by Antigravity.',
    features: ['Premium Quality', 'Durable', 'Authentic Design', 'High Ratings'],
    image: '/products/yoga_mat.png',
    rating: 4.0,
    reviewCount: 465,
    inStock: true,
  },
};

export const PRODUCTS_LIST = Object.values(PRODUCTS);

export const CATEGORIES = [
  { slug: 'fashion', name: 'Fashion & Apparel', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='fashion').length },
  { slug: 'accessories', name: 'Luxury Accessories', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='accessories').length },
  { slug: 'kitchen', name: 'Kitchen & Appliances', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='kitchen').length },
  { slug: 'electronics', name: 'Electronics', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='electronics').length },
  { slug: 'furniture', name: 'Furniture', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='furniture').length },
  { slug: 'footwear', name: 'Footwear', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='footwear').length },
  { slug: 'fitness', name: 'Fitness', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='fitness').length },
  { slug: 'home-decor', name: 'Home & Decor', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='home-decor').length },
  { slug: 'bags-travel', name: 'Bags & Travel', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='bags-travel').length },
  { slug: 'audio', name: 'Audio', count: PRODUCTS_LIST.filter(p=>p.categorySlug==='audio').length },
];

export function getProductsByCategory(slug: string): Product[] {
  return PRODUCTS_LIST.filter(index => index.categorySlug === slug);
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase();
  return PRODUCTS_LIST.filter(product => 
    product.name.toLowerCase().includes(lowercaseQuery) || 
    product.category.toLowerCase().includes(lowercaseQuery) ||
    product.description.toLowerCase().includes(lowercaseQuery)
  );
}

export function getRelatedProducts(productId: string, limit = 4): Product[] {
  const currentProduct = PRODUCTS[productId];
  if (!currentProduct) return [];
  
  return PRODUCTS_LIST
    .filter(p => p.id !== productId && p.categorySlug === currentProduct.categorySlug)
    .slice(0, limit);
}
